# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-12 23:17
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=50)),
                ('isActive', models.IntegerField(default=0)),
                ('activationcode', models.CharField(default='', max_length=20)),
                ('gameboard', models.CharField(max_length=100)),
                ('first_time', models.DateTimeField(default=datetime.datetime(2017, 2, 12, 23, 17, 2, 246738), max_length='50')),
            ],
        ),
    ]
